// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

/*
Package proto_raft is a generated protocol buffer package.

It is generated from these files:
	raft.proto

It has these top-level messages:
	AppendEntriesRequest
	LogEntry
	AppendEntriesResponse
	RequestVoteRequest
	RequestVoteResponse
*/
package proto_raft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppendEntriesRequest struct {
	// Leader's term
	Term int64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	// This is so that follower can redirect clients. Leader ID is hostname/IP + Port number of the
	// the leader. E.g. something like 10.10.1.2:50103
	LeaderId string `protobuf:"bytes,2,opt,name=leaderId" json:"leaderId,omitempty"`
	// Index of the log entry immediately preceeding the new ones
	PrevLogIndex int64 `protobuf:"varint,3,opt,name=prevLogIndex" json:"prevLogIndex,omitempty"`
	// Term of prevLogIndex entry
	PrevLogTerm int64 `protobuf:"varint,4,opt,name=prevLogTerm" json:"prevLogTerm,omitempty"`
	// Log entries to store. This can be empty for just for heartbeat messages.
	// Can send more than one for efficiency reasons.
	Entries []*LogEntry `protobuf:"bytes,5,rep,name=entries" json:"entries,omitempty"`
	// Leaders commit index.
	LeaderCommit int64 `protobuf:"varint,6,opt,name=leaderCommit" json:"leaderCommit,omitempty"`
}

func (m *AppendEntriesRequest) Reset()                    { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()               {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppendEntriesRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *AppendEntriesRequest) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesRequest) GetLeaderCommit() int64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type LogEntry struct {
	// Data to be appended to the replicated log.
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogEntry) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type AppendEntriesResponse struct {
	// RPC response code status. See https://godoc.org/google.golang.org/grpc/codes
	ResponseStatus int64 `protobuf:"varint,1,opt,name=responseStatus" json:"responseStatus,omitempty"`
	// Current term for leader to update itself.
	Term int64 `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
	// True if follower contained entry matching prevLogIndex and prevLogTerm
	Success bool `protobuf:"varint,3,opt,name=success" json:"success,omitempty"`
}

func (m *AppendEntriesResponse) Reset()                    { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()               {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppendEntriesResponse) GetResponseStatus() int64 {
	if m != nil {
		return m.ResponseStatus
	}
	return 0
}

func (m *AppendEntriesResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// This invoked by candidated to gather votes.
type RequestVoteRequest struct {
	// Candidate's term
	Term int64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	// Candidate requesting the vote.
	// This is the fully qualified name for the node (hostname/ip + port number).
	CandidateId string `protobuf:"bytes,2,opt,name=candidateId" json:"candidateId,omitempty"`
	// Index of candidate's last log entry
	LastLogIndex int64 `protobuf:"varint,3,opt,name=lastLogIndex" json:"lastLogIndex,omitempty"`
	// Term of candidate's last log entry
	LastLogTerm int64 `protobuf:"varint,4,opt,name=lastLogTerm" json:"lastLogTerm,omitempty"`
}

func (m *RequestVoteRequest) Reset()                    { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()               {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestVoteRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

func (m *RequestVoteRequest) GetLastLogIndex() int64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogTerm() int64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	// RPC response code status. See https://godoc.org/google.golang.org/grpc/codes
	ResponseStatus int64 `protobuf:"varint,1,opt,name=responseStatus" json:"responseStatus,omitempty"`
	// Current term for candidate to update themselves.
	Term int64 `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
	// If true, indicates that the node has voted for the candidate to be a leader.
	VoteGranted bool `protobuf:"varint,3,opt,name=voteGranted" json:"voteGranted,omitempty"`
}

func (m *RequestVoteResponse) Reset()                    { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()               {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RequestVoteResponse) GetResponseStatus() int64 {
	if m != nil {
		return m.ResponseStatus
	}
	return 0
}

func (m *RequestVoteResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResponse) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

func init() {
	proto.RegisterType((*AppendEntriesRequest)(nil), "proto_raft.AppendEntriesRequest")
	proto.RegisterType((*LogEntry)(nil), "proto_raft.LogEntry")
	proto.RegisterType((*AppendEntriesResponse)(nil), "proto_raft.AppendEntriesResponse")
	proto.RegisterType((*RequestVoteRequest)(nil), "proto_raft.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "proto_raft.RequestVoteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Raft service

type RaftClient interface {
	// Sends an AppendEntries RPC.
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
	// Send a RequestVote RPC.
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := grpc.Invoke(ctx, "/proto_raft.Raft/AppendEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := grpc.Invoke(ctx, "/proto_raft.Raft/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Raft service

type RaftServer interface {
	// Sends an AppendEntries RPC.
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	// Send a RequestVote RPC.
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_raft.Raft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_raft.Raft/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_raft.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0xae, 0xd3, 0x30,
	0x10, 0xc6, 0x49, 0x5b, 0xfa, 0x67, 0x02, 0x2c, 0x4c, 0x91, 0xa2, 0x2e, 0x4a, 0xc8, 0x02, 0x75,
	0x43, 0x16, 0xe5, 0x04, 0x14, 0x21, 0x54, 0xa9, 0x8b, 0x2a, 0xa0, 0x6e, 0x91, 0x1b, 0x4f, 0x4b,
	0xa4, 0x26, 0x4e, 0xed, 0x49, 0x05, 0xb7, 0xe0, 0x28, 0x1c, 0x89, 0xa3, 0x20, 0x3b, 0x49, 0x9f,
	0xdb, 0xf7, 0x5e, 0x57, 0x6f, 0x15, 0xcf, 0x67, 0xcf, 0xf8, 0xfb, 0x7e, 0x0e, 0x80, 0xe2, 0x3b,
	0x8a, 0x4b, 0x25, 0x49, 0x32, 0xb0, 0x9f, 0x1f, 0x46, 0x89, 0xfe, 0x79, 0x30, 0xfe, 0x54, 0x96,
	0x58, 0x88, 0x2f, 0x05, 0xa9, 0x0c, 0x75, 0x82, 0xc7, 0x0a, 0x35, 0x31, 0x06, 0x3d, 0x42, 0x95,
	0x07, 0x5e, 0xe8, 0xcd, 0xba, 0x89, 0x5d, 0xb3, 0x09, 0x0c, 0x0f, 0xc8, 0x05, 0xaa, 0xa5, 0x08,
	0x3a, 0xa1, 0x37, 0x1b, 0x25, 0xe7, 0x9a, 0x45, 0xf0, 0xa2, 0x54, 0x78, 0x5a, 0xc9, 0xfd, 0xb2,
	0x10, 0xf8, 0x2b, 0xe8, 0xda, 0xbe, 0x0b, 0x8d, 0x85, 0xe0, 0x37, 0xf5, 0x77, 0x33, 0xba, 0x67,
	0x8f, 0xb8, 0x12, 0x8b, 0x61, 0x80, 0xb5, 0x8f, 0xe0, 0x79, 0xd8, 0x9d, 0xf9, 0xf3, 0x71, 0x7c,
	0x67, 0x36, 0x5e, 0xc9, 0xbd, 0x71, 0xf9, 0x3b, 0x69, 0x0f, 0x99, 0x5b, 0x6b, 0x07, 0x9f, 0x65,
	0x9e, 0x67, 0x14, 0xf4, 0xeb, 0x5b, 0x5d, 0x2d, 0x9a, 0xc2, 0xb0, 0x6d, 0x34, 0xa9, 0x04, 0x27,
	0x6e, 0x53, 0x8d, 0x12, 0xbb, 0x8e, 0x72, 0x78, 0x73, 0x45, 0x40, 0x97, 0xb2, 0xd0, 0xc8, 0xde,
	0xc3, 0x2b, 0xd5, 0xac, 0xbf, 0x11, 0xa7, 0x4a, 0x37, 0x30, 0xae, 0xd4, 0x33, 0xaa, 0x8e, 0x83,
	0x2a, 0x80, 0x81, 0xae, 0xd2, 0x14, 0xb5, 0xb6, 0x24, 0x86, 0x49, 0x5b, 0x46, 0x7f, 0x3c, 0x60,
	0x0d, 0xe4, 0x8d, 0x24, 0xbc, 0xc5, 0x3b, 0x04, 0x3f, 0xe5, 0x85, 0xc8, 0x04, 0x27, 0x3c, 0x23,
	0x77, 0x25, 0x9b, 0x9f, 0x6b, 0xba, 0xa6, 0xee, 0x6a, 0x66, 0x4a, 0x53, 0xbb, 0xd4, 0x1d, 0x29,
	0xd2, 0xf0, 0xfa, 0xc2, 0xd1, 0x13, 0xe4, 0x0f, 0xc1, 0x3f, 0x49, 0xc2, 0xaf, 0x8a, 0x17, 0x84,
	0xa2, 0x61, 0xe0, 0x4a, 0xf3, 0xbf, 0x1e, 0xf4, 0x12, 0xbe, 0x23, 0xb6, 0x81, 0x97, 0x17, 0xfc,
	0x59, 0xe8, 0xbe, 0xf9, 0x43, 0x3f, 0xe7, 0xe4, 0xdd, 0x8d, 0x13, 0xb5, 0xb5, 0xe8, 0x19, 0x5b,
	0x83, 0xef, 0xa4, 0x62, 0x53, 0xb7, 0xe7, 0xfe, 0x03, 0x4c, 0xde, 0x3e, 0xba, 0xdf, 0x4e, 0x5c,
	0x7c, 0x80, 0x69, 0x2a, 0xf3, 0x78, 0x9f, 0xd1, 0xcf, 0x6a, 0x1b, 0x2b, 0xd4, 0xc7, 0x43, 0x46,
	0x58, 0xf7, 0xc5, 0xa6, 0x6f, 0x31, 0x32, 0x89, 0xd6, 0xa6, 0x5e, 0x7b, 0xdb, 0xbe, 0xdd, 0xf8,
	0xf8, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x7b, 0x41, 0xa4, 0x7c, 0x03, 0x00, 0x00,
}
